config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/auth/twitter/callback', to: 'sessions#create'
  get '/auth/facebook/callback', to: 'sessions#create'

  get 'about' => 'welcome#about'
  get 'events/filter' => 'events#filter'
  resources :users, :events, :rsvps
  resources :sessions, only: [:new, :create, :destroy]
  resources :search, only: [:new, :index]

end

app/models/event.rb
class Event < ActiveRecord::Base
	require 'textacular'
	has_many :rsvps
  has_many :users, :through => :rsvps
  scope :current, -> {where("date >= ?", Date.today)}
  validates :event_name, :sport, :start, :location, :date, presence: true
  validates :participants, :numericality => { :greater_than =>0}
  validate :start_before_end

  def creator
    User.find(self.creator_id)
  end

  def start_before_end
    if self.end && self.end < start
      errors.add(:start, "Invalid end time")
    end
  end

  geocoded_by :location
  after_validation :geocode

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name,  presence: true
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true, length: { minimum: 6 }
	has_secure_password
  has_many :rsvps
  has_many :events, :through => :rsvps

  def created_events
    Event.where(creator_id: self.id)
  end

  def self.from_omniauth(auth_hash)
    user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
    #will update user's details if there are any social media profile changes
    fullname = auth_hash['info']['name'].split(" ")
    user.first_name = fullname[0]
    if fullname.length > 1
      user.last_name = fullname[1..fullname.length-1].join(" ")
    else
      user.last_name = " "
    end
    user.email = "#{auth_hash['uid']}@#{auth_hash['provider']}.com"
    user.password = auth_hash['uid']
    user.save!
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
    #used to change navbar options based on whether a user is logged in
  end

  def require_user
  	redirect_to '/' unless current_user
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :current_user, :require_user, only: [:index, :show, :new, :edit, :filter]

  def index
    if request.xhr?
      coords = params[:latitude] + ", " + params[:longitude] #takes the longitude and lat from the AJAX call and concatenates them into a string
      @nearevents = Event.current.near(coords, 20, :order => "distance").limit(10) #Runs the coords in Geocoder to find all events within 20(2nd arg) miles. It then sorts them by distance and limits the return array to 10 items. This also passes @nearevents into the function below.
      render :json => {:partial => render_to_string(:partial => 'events/nearevents')}
    end
  end

  def create
    @event = Event.new(event_params)
    @event.creator_id = current_user.id
    if @event.save
      UserMailer.event_creation_email(User.find(current_user.id), @event).deliver_now
      Rsvp.create(event_id: @event.id, user_id: @event.creator_id)
      redirect_to events_path
    else
      flash[:notice] = @event.errors.full_messages
      redirect_to new_event_path
    end
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    @alreadyjoined = @event.users.where(id: current_user.id).length == 0
    @openevent = @event.users.size < @event.participants
  end

  def destroy
    @event = Event.find(params[:id]).destroy
  end

  def update
    @event = Event.find(params[:id])
    @event.update_attributes(event_params)
    redirect_to @event
  end

  def edit
    @event = Event.find(params[:id])
  end

  def filter
    if request.xhr?
      case params[:key]
      when "sport"
        @eventmatch = Event.current.where(sport: params[:sport]).order('event_name asc')
      when "location"
        @eventmatch = Event.current.near("#{params[:lat]} , #{params[:long]}", (params[:location].to_i), :order => "distance") #converts the params into a long/lat sequence and pulls
      when "date"
        @eventmatch = Event.where(date: eval(params[:date])).order('date asc')
      else
        @eventmatch = Event.current.order('event_name asc')
      end
      render :json => {:partial => render_to_string(:partial => 'events/filterresults')}
    else
      @events = Event.current.order('event_name asc')
    end
  end

  private
    def event_params
      params.require(:event).permit(:event_name, :description, :sport, :start, :end, :date, :participants, :location)
    end
end

app/controllers/rsvps_controller.rb
include RsvpsHelper

class RsvpsController < ApplicationController
  before_action :current_user
  def create
    event = Event.find(params[:id])
    unless event.users.exists?(current_user)
      Rsvp.create(user_id: current_user.id, event_id: params[:id])
      flash[:notice] = "You have joined this event!"
      UserMailer.event_confirm_email(User.find(current_user.id), event).deliver_now
      UserMailer.join_notification(event.creator, event).deliver_now
    end
    redirect_to user_path(current_user)
  end

  def destroy
    event = Event.find(params[:id])
    tbd = Rsvp.where(event_id: params[:id], user_id: current_user.id)
    Rsvp.delete(tbd)
    if event.creator_id == current_user.id
      @attendees = event.users.size
      if @attendees >= 1
        new_host = Rsvp.where(event_id:params[:id]).order('created_at ASC')[0].user_id
        event.update_attribute(:creator_id, new_host)
      else
        event.destroy
      end
    end
    redirect_to user_path(current_user)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
before_action :current_user
  def new
  end

  def index
    @events = Event.current.basic_search(params[:search][:description])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :current_user
	def new
	end

	def create
		if request.env['omniauth.auth']
			@user = User.from_omniauth(request.env['omniauth.auth'])
    	session[:user_id] = @user.id
    	redirect_to events_path
		else
			@user = User.find_by_email(params[:session][:email])
			if @user && @user.authenticate(params[:session][:password])
				session[:user_id] = @user.id
				redirect_to events_path
			else
				flash[:notice] = "Username or Password was incorrect. Try Again."
				redirect_to root_path
			end
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You have been logged out"
		redirect_to '/'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :current_user

	def show
		@user = User.find_by(id: params[:id])
		@ownedevents = @user.created_events.current.order('date asc')
		@joinedevents = @user.events.current.order('date asc')
		if @user && @user == current_user
		else
			flash[:notice] = "Access Denied."
			redirect_to '/'
		end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to '/'
			UserMailer.welcome_email(@user).deliver_now
		else
			flash[:notice] = "Failed to create a new account. Try Again."
			redirect_to '/'
		end
	end

	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :current_user
  def index
    if current_user
      redirect_to events_path
    end
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
  # def creator_leave
  #   @event = Event.find(params[:id])
  #   @event.users.destroy(User.find(current_user.id))
  #   @new_host = @event.users.first
  #   @attendees = @event.users.size

  #   if @attendees >= 1
  #     @event.update_attribute(:creator_id, @new_host.id)
  #     @event.save
  #   else
  #     @event.destroy
  #   end
  #   redirect_to user_path(current_user)
  # end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_filterresults.html.erb
<table class="table table-striped" id ="allevents">
  <tr>
    <th class="item col-xs-1 centercolumn">Event name</th>
    <th class="item col-xs-1 centercolumn">Activity</th>
    <th class="item col-xs-1 centercolumn">Location</th>
    <th class="item col-xs-1 centercolumn">Date</th>
    <th class="item col-xs-1 centercolumn">Start time</th>
  </tr>
  <%@eventmatch.each do |event|%>
    <tr>
      <td><%=link_to event.event_name, event_path(event)%></td>
      <td><%=event.sport%></td>
      <td><%=event.location%></td>
      <td><%=event.date.strftime("%A %m/%d/%Y")%></td>
      <td><%=event.start.strftime("%I:%M %P ")%></td>
    </tr>
  <%end%>
</table>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
<div class="form-group">
  <%= f.label :event_name %><br>
  <%= f.text_field :event_name, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :description %><br>
  <%= f.text_field :description, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :sport %><br>
  <%= f.select :sport, ["Basketball", "Baseball", "Football", "Soccer", "PingPong", "Volleyball", "Tennis", "Golf", "Bowling", "Misc"], {prompt: "Select sport"}, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :start %><br>
  <%= f.time_select :start, {:ampm => true}  %>
</div>

<div class="form-group">
  <%= f.label :end %><br>
  <%= f.time_select :"end", {:ampm => true} %>
</div>

<div class="form-group">
  <%= f.label :date %><br>
  <%= f.text_field :date, "data-provide" => "datepicker", 'data-date-format'=>"yyyy/mm/dd", class: "form-control"%>
</div>

<div class="form-group">
  <%= f.label :participants %><br>
  <%= f.text_field :participants, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :location %><br>
  <%= f.text_field :location, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.submit class: "btn-success" %>
</div>
<% end %>

app/views/events/_map.html.erb
<%= javascript_include_tag 'events/mapsetup.js'%>
<div id="wrapper">
  <div id="sidebar-wrapper">
    <div id = "mappp" style="height: 100%;" align="center"></div>
  </div>
  <div id="page-content-wrapper">
    <div class="row col-lg-12">
      <div class="col-lg-1 text-right"></div>
      <div class="col-lg-5 text-left">
        <div class="event-buttons"><h1>Events near you:</h1></div>
      </div>
      <div class="col-lg-3 text-right"></div>
      <div class="col-lg-2">
        <div class="event-buttons pull-right"><%= button_to "Create an event", new_event_path, method: "get", class: "" %>
        <%= button_to "See all events", events_filter_path, method: "get", class: "" %>
        </div>
      </div>
      <div class="col-lg-1 text-right"></div>
    </div>
    <div class="page-content">
      <div class="container">
        <div class="row col-lg-12 nearby-event-page" >
            <%@nearevents.each do |event|%>
              <div class="col-lg-5 event-card" id="<%=event.sport%>" href="event">
                <h1><%=link_to event.event_name.capitalize, event_path(event)%></h1>
                <h5 class="eventcard">
                  <%=event.sport%> <%=event.date.strftime("%m/%d")%>
                </h5>
                <h2 class=" pinnn">
                  <%= link_to "Show", class: "showme glyphicon glyphicon-map-marker", data: {lat: event.latitude, long: event.longitude} do %>
                <% end %>
                </h2>
              </div>
            <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_nearevents.html.erb
<%= javascript_include_tag 'events/mapsetup.js'%>
<div id="wrapper">
  <div id="sidebar-wrapper">
    <div id = "mappp" style="height: 100%;" align="center"></div>
  </div>
  <div id="page-content-wrapper">
    <div class="row col-lg-12">
      <div class="col-lg-1 text-right"></div>
      <div class="col-lg-5 text-left">
        <div class="event-buttons"><h1>Events near you:</h1></div>
      </div>
      <div class="col-lg-3 text-right"></div>
      <div class="col-lg-2">
        <div class="event-buttons pull-right"><%= button_to "Create an event", new_event_path, method: "get", class: "" %>
        <%= button_to "See all events", events_filter_path, method: "get", class: "" %>
        </div>
      </div>
      <div class="col-lg-1 text-right"></div>
    </div>
    <div class="page-content">
      <div class="container">
        <div class="row col-lg-12 nearby-event-page" >
            <%@nearevents.each do |event|%>
              <div class="col-lg-5 event-card" id="<%=event.sport%>" href="event">
                <h1><%=link_to event.event_name.capitalize, event_path(event)%></h1>
                <h5 class="eventcard">
                  <%=event.sport%> <%=event.date.strftime("%m/%d")%>
                </h5>
                <h2 class=" pinnn">
                  <%= link_to "Show", class: "showme glyphicon glyphicon-map-marker", data: {lat: event.latitude, long: event.longitude} do %>
                <% end %>
                </h2>
              </div>
            <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <div class="form-group">
  <h1> Edit Event: <%= @event.event_name %> </h1>
  <%= render 'form' %>
</div>

app/views/events/filter.html.erb
<%= javascript_include_tag 'eventfilters/filtering.js'%>
<table id="filters">
  <tr>
    <td>
      Sport
      <br>
      <select name="sportmenu" id="sport">
        <option value="start"></option>
        <option value="Baseball">Baseball</option>
        <option value="Basketball">Basketball</option>
        <option value="Bowling">Bowling</option>
        <option value="Football">Football</option>
        <option value="Golf">Golf</option>
        <option value="PingPong">PingPong</option>
        <option value="Soccer">Soccer</option>
        <option value="Tennis">Tennis</option>
        <option value="Volleyball">Volleyball</option>
        <option value="Misc">Misc</option>
      </select>
    </td>
    <td>
      Distance
      <br>
      <select name="locationmenu" id="location">
        <option value="start"></option>
        <option value="5">Under 5 miles</option>
        <option value="20">Under 20 miles</option>
        <option value="40">Under 40 miles</option>
        <option value="100">Under 100 miles</option>
      </select>
      </td>
    <td>
      Event Start
      <br>
      <select name="datemenu" id="date">
        <option value="start"></option>
        <option value="Date.today..1.week.from_now">This week</option>
        <option value="Date.today..2.weeks.from_now">In the next two weeks</option>
        <option value="Date.today..3.weeks.from_now">In the next three weeks</option>
        <option value="Date.today..1.month.from_now">In a month</option>
      </select>
    </td>
    <td><%=link_to 'Remove Filter', "remove", :id => 'clear' %></td>
  </tr>
</table>
<div class="">
<table class="table table-striped table-condensed table-responsive" id ="allevents">
<tr>
  <th class="item col-lg-2 centercolumn">Event name</th>
  <th class="item col-lg-2 centercolumn">Activity</th>
  <th class="item col-lg-2 centercolumn">Participant numbers</th>
  <th class="item col-lg-2 centercolumn">Location</th>
  <th class="item col-lg-2 centercolumn">Date</th>
  <th class="item col-lg-2 centercolumn">Start time</th>
</tr>
  <%@events.each do |event|%>
    <tr>
      <td><%=link_to event.event_name, event_path(event)%></td>
      <td><%=event.sport%></td>
      <td><%=event.users.size %> / <%= event.participants %> </td>
      <td><%=event.location.upcase%></td>
      <td><%=event.date.strftime("%A %m/%d/%Y")%></td>
      <td><%=event.start.strftime("%I:%M %P")%></td>
    </tr>
  <%end%>
</table>
</div>

app/views/events/index.html.erb
<%= javascript_include_tag 'events/geolocate.js'%>
<div class="row">
  <div id = "nearevents"></div>
</div>

app/views/events/new.html.erb
<div class="new-event-container">
	<h1> Create a new event: </h1>
	<%= render 'form' %>
</div>

app/views/events/show.html.erb
<%= javascript_include_tag 'events/showevent.js'%>

<div class="col-md-12">
  <div class ="row">
    <div class="col-md-4">
      <h1> <%=@event.event_name.capitalize%> </h1>
    </div>
  </div>
  <div class ="row">
    <div class="col-md-4">
      <div class="table">
        <table class="event-table" style>
          <tr>
            <td><b>Event Details: </b></td>
          </tr>
          <tr>
            <td>Host: <%= @event.creator.first_name.capitalize %></td>
          </tr>
          <tr>
            <td>Sport: <%= @event.sport %></td>
          </tr>
          <%if @event.description %>
          <tr>
            <td>Description: <%= @event.description %></td>
          </tr>
          <%end%>
          <tr>
            <td>Start: <%= @event.start.strftime("%I:%M %P") %></td>
          </tr>
          <%if @event.end %>
          <tr>
            <td>End: <%= @event.end.strftime("%I:%M %P") %></td>
          </tr>
          <%end%>
          <tr>
            <td>Date: <%= @event.date.strftime("%m/%d/%Y") %></td>
          </tr>
          <tr>
            <td>Participants: <%= @event.users.size %> / <%=@event.participants%></td>
          </tr>
          <tr>
            <td>Location: <%= @event.location.upcase %></td>
          </tr>
        </table>
        <div class="panel panel-default">
          <div class="panel-heading"><b>Attending: </b></div>
            <ul class="list-group">
              <% @event.users.each do |e| %>
              <li class="list-group-item"><%= e.first_name.capitalize%>  email: <%=e.email%></li>
              <% end %>
            </ul>
        </div>
          <%if @alreadyjoined %>
            <%if @openevent %>
              <td class="col-md-1" id='index_join'>
                <%= button_to "Join", rsvps_path(id: @event.id), id: "index_join_button", method: :post%>
              </td>
            <% else %>
              <td class="col-md-1" id='index_join'>This event is full.</td>
            <% end %>
          <% else %>
            <td class="col-md-1">
              <%= button_to "leave", rsvp_path(id: @event.id), method: :delete %>
            </td>
          <% end %>
        </div>
      </div>
    <div class="col-md-8">
      <div id="map2" style="height: 500px; width: 500px;"></div>
    </div>
  </div>
</div>

<%if flash[:notice]%>
  <div class="flash-error"><h3><%= flash[:notice]%></h3></div>
<% end %>

<%= content_tag :div, id: "event-info", data: {lat_info: @event.latitude, lng_info: @event.longitude} do %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PickUp</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCE-897CDl9CnFtZDVIQEQkd409ibKqcmQ" type="text/javascript"></script>
</head>
<body>
<nav class="navbar navbar-fixed-top navbar-inverse" id="the-navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'PickUp!', root_path, class: "navbar-brand"%>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if @current_user %>
        <div class="navbar-form navbar-left" role="search">
          <div class="input-group">
            <div><%=render 'search/new'%></div>
          </div>
        </div>
      <% end %>
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if @current_user %>
            <li><%= link_to 'Home', events_path %></li>
            <li class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hi, <%=@current_user.first_name.capitalize%> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li class="text-center"><%= link_to "My Profile", user_path(@current_user)%></li>
                  <li class="text-center"><%= link_to "About", about_path %> </li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", session_path(:user), method: "delete", class: "btn navbar-btn" %></li>
                </ul>
            </li>
          <% else %>
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Login", new_session_path, class:"logmein" %></li>
            <li><%= link_to "Register", new_user_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% if current_page?(controller: 'events', action:'filter') %>
    <div class="container-fluid alleventsbanner col-xs-12">
      <h1> All Events </h1>
    </div>
  <%end%>

  <% if current_page?(controller: 'search', action:'index') %>
    <div class="container-fluid alleventsbanner col-xs-12">
      <h1>Search Results</h1>
    </div>
  <%end%>

  <header>
    <%if flash[:notice]%>
      <%= flash[:notice]%>
    <% end %>
  </header>

  <div id="login">
    <div>
      <div class="form-group">
        <h4>Please login<h4>
        <%= form_for(:session, url: sessions_path, method: :post) do |f| %>
          <%= f.email_field :email, :placeholder => "Email", class: "form-control"%><br>
          <%= f.password_field :password, :placeholder => "Password", class: "form-control"%> <br>
          <%= f.submit "Log in",  class: "btn btn-success", "style" => "width: 180px"%>
        <% end %>
      </div>
      <div class="social-button"><%= link_to image_tag("facebook.png"), '/auth/facebook'%></div><br>
      <div class="social-butoon"><%= link_to image_tag("twitter.png"), '/auth/twitter'%></div>
      <br>
      <div><a href="" id="cancel">Cancel</a></div>
    </div>
  </div>


  <% if current_page?(controller: 'welcome', action:'index') %>
    <%=  yield  %>
  <% else %>
  <div class="container-fluid">
    <%= yield%>
  </div>
  <%end %>


</body>
</html>

app/views/search/_new.html.erb
<%=form_for :search, url: search_index_path, method: 'get' do |f|%>
  <%=f.text_field :description, :placeholder => "Search Events", class: "form-control" %>
  <%=f.submit 'Search',  class: "btn btn-default form-control"%>
<%end%>

app/views/search/index.html.erb
<table class="search-results table table-striped table-responsive">
  <tr>
    <th class="item col-xs-2 centercolumn">Event name</th>
    <th class="item col-xs-2 centercolumn">Activity</th>
    <th class="item col-xs-3 centercolumn">Location</th>
    <th class="item col-xs-2 centercolumn">Date</th>
    <th class="item col-xs-2 centercolumn">Start time</th>
  </tr>
  <%@events.each do |event|%>
  <tr>
    <td class='centercolumn'><%=link_to event.event_name.capitalize, event_path(event)%></td>
    <td class='centercolumn'><%=event.sport%></td>
    <td class='centercolumn'><%=event.location.upcase%></td>
    <td class='centercolumn'><%=event.date.strftime("%A %m/%d/%Y")%></td>
    <td class='centercolumn'><%=event.start.strftime("%I:%M %P ")%></td>
  </tr>
  <%end%>
</table>

app/views/users/show.html.erb
<div class="container">
	<div class="row" id="create-event">
		<h1> <%= @user.first_name.capitalize %>'s Profile</h1>
		<div class="col-md-12">
		<div class="row">
			<div class="table">
				<table class="table table-striped text-center">
					<tr><h2>My Events</h2></tr>
					<thead>
						<tr>
							<td class="col-md-2">Date</td>
							<td class="col-md-2">Event Name</td>
							<td class="col-md-1">Time</td>
							<td class="col-md-2">Location</td>
							<td class="col-md-1">Attending</td>
							<td class="col-md-1"></td>
							<td class="col-md-1"></td>
						</tr>
					</thead>

					<tbody>
						<% @ownedevents.each do |event| %>
						<tr>
							<td><%= event.date.strftime("%A  %m/%d/%Y") %></td>
							<td><%= link_to event.event_name.capitalize, event_path(event.id) %></td>
							<td><%= event.start.strftime("%I:%M %P") %></td>
							<td><%= event.location.upcase %></td>
							<td><%= event.users.size %> / <%= event.participants %></td>
							<td class="col-md-1"><%= button_to "edit", edit_event_path(event.id), method: "get" %></td>
							<td class="col-md-1"><%= link_to "leave", rsvp_path(id: event.id), method: "delete" %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
      	<%= button_to "Create an event", new_event_path, method: "get", class: "btn-info pull-right" %>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="row" id="create-event">
		<div class="col-md-12">
			<div class="row">
				<table class="table table-striped text-center">
					<tr><h2>Joined Events</h2></tr>
					<thead>
						<tr>
							<td class="col-md-2">Date</td>
							<td class="col-md-2">Event Name</td>
							<td class="col-md-2">Time</td>
							<td class="col-md-3">Location</td>
							<td class="col-md-1">Host</td>
							<td class="col-md-1">Attending</td>
							<td class="col-md-1"></td>
						</tr>
					</thead>

					<tbody>
						<% @joinedevents.each do |event| %>
						<tr>
							<td><%= event.date.strftime("%A %m/%d/%Y") %></td>
							<td><%= link_to event.event_name.capitalize, event_path(event.id) %></td>
							<td><%= event.start.strftime("%I:%M %P") %></td>

							<td><%= event.location.upcase %></td>
							<td><%= (event.creator).first_name.capitalize %> </td>
							<td><%= event.users.size %> / <%= event.participants %> </td>
							<td class="col-md-1"><%= button_to "leave", rsvp_path(id: event.id), method: "delete" %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
				<div class="col-md-1 pull-right">
        	<%= button_to "Nearby Events", events_path, method: "get", class: "btn-info"%>
        </div>
				<div class="pull-right">
        	<%= button_to "All events", events_filter_path, method: "get", class: "btn-info"%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
  </div>
  <div class="cover-container">
    <div class="inner cover">
      <h1 class="cover-heading text-shadow-format">Pick Up!</h1>
      <p class="lead">
        <%=link_to 'Register', new_user_path, class:"btn btn-lg btn-default spacer"%>

        <%=link_to 'Login', new_session_path, class:"btn btn-lg btn-default spacer logmein"%>
      </p>
      <p class="lead text-shadow-format">A whole new way to find activities
      </p>
      <p class="lead">
        <%=link_to 'Learn More', about_path, class:"btn btn-lg btn-default"%>
      </p>
    </div>
  </div>
  <div class="site-wrapper-bottom">
  </div>
</div>